import type { ComponentRegistryEntry } from "./component-registry.js";
import type { CapabilityId, PortId } from "../types/ids.js";
import type { ConditionProfile } from "../types/condition.js";

const defaultProfile: ConditionProfile = {
  degradedThreshold: 0.6,
  criticalThreshold: 0.3,
  decayRate: 0.05,
  recoveryRate: 0.02,
  degradedEffects: [{ kind: "latency_multiplier", factor: 1.5 }],
  criticalEffects: [
    { kind: "latency_multiplier", factor: 3 },
    { kind: "drop_probability", p: 0.2 },
  ],
};

const resilientProfile: ConditionProfile = {
  degradedThreshold: 0.5,
  criticalThreshold: 0.2,
  decayRate: 0.03,
  recoveryRate: 0.03,
  degradedEffects: [{ kind: "latency_multiplier", factor: 1.3 }],
  criticalEffects: [
    { kind: "latency_multiplier", factor: 2 },
    { kind: "drop_probability", p: 0.15 },
  ],
};

function cap(id: string, defaultTier: number, maxTier: number) {
  return { id: id as CapabilityId, defaultTier, maxTier };
}

function port(id: string, direction: "ingress" | "egress", dataType: string, capacity: number) {
  return { id: id as PortId, direction, dataType, capacity, connections: [] as import("../types/ids.js").ConnectionId[] };
}

export const COMPONENT_ENTRIES: ComponentRegistryEntry[] = [
  {
    type: "client",
    name: "Client",
    description: "Traffic entry point. Forwards requests into the architecture.",
    capabilities: [cap("forwarding", 1, 1)],
    ports: [port("out", "egress", "http", 100)],
    placementCost: 0,
    upgradeCostCurve: [],
    visual: { icon: "client", color: "#94a3b8", shape: "circle" },
    conditionProfile: defaultProfile,
  },
  {
    type: "server",
    name: "Server",
    description: "General-purpose compute workhorse. Handles any request type.",
    capabilities: [
      cap("retry", 0, 2),
      cap("processing", 1, 3),
      cap("monitoring", 1, 2),
      cap("auto-scale", 0, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "data", 100)],
    placementCost: 100,
    upgradeCostCurve: [0, 100, 200, 400],
    visual: { icon: "server", color: "#3b82f6", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "database",
    name: "Database",
    description: "Persistent structured data storage. Required for write operations.",
    capabilities: [
      cap("storage", 1, 3),
      cap("search", 0, 2),
      cap("replication", 0, 3),
      cap("sharding", 0, 2),
      cap("query", 0, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "data", 100), port("out", "egress", "data", 100)],
    placementCost: 200,
    upgradeCostCurve: [0, 200, 400, 800],
    visual: { icon: "database", color: "#8b5cf6", shape: "cylinder" },
    conditionProfile: defaultProfile,
  },
  {
    type: "cache",
    name: "Cache",
    description: "Remembers recent responses. Intercepts repeated reads before they hit the server.",
    capabilities: [
      cap("caching", 1, 3),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "data", 100), port("out", "egress", "data", 100)],
    placementCost: 150,
    upgradeCostCurve: [0, 150, 300, 600],
    visual: { icon: "cache", color: "#f59e0b", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "load_balancer",
    name: "Load Balancer",
    description: "Distributes traffic across multiple servers. Absorbs reverse-proxy duties via upgrades.",
    capabilities: [
      cap("ssl-termination", 0, 2),
      cap("compression", 0, 2),
      cap("filter", 0, 2),
      cap("rate-limit", 0, 3),
      cap("routing", 1, 3),
      cap("forwarding", 1, 1),
      cap("health-check", 1, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "http", 100)],
    placementCost: 175,
    upgradeCostCurve: [0, 175, 350, 700],
    visual: { icon: "load-balancer", color: "#06b6d4", shape: "diamond" },
    conditionProfile: defaultProfile,
  },
  {
    type: "queue",
    name: "Message Queue",
    description: "Buffers traffic spikes. Trades speed for survival.",
    capabilities: [
      cap("queue", 1, 3),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "any", 100), port("out", "egress", "any", 100)],
    placementCost: 125,
    upgradeCostCurve: [0, 125, 250, 500],
    visual: { icon: "queue", color: "#f97316", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "cdn",
    name: "CDN",
    description: "Edge cache for static assets. ~10x efficiency for cacheable content.",
    capabilities: [
      cap("filter", 1, 1),
      cap("caching", 1, 2),
      cap("forwarding", 1, 1),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "http", 100)],
    placementCost: 200,
    upgradeCostCurve: [0, 200, 400],
    visual: { icon: "cdn", color: "#10b981", shape: "hexagon" },
    conditionProfile: resilientProfile,
  },
  {
    type: "api_gateway",
    name: "API Gateway",
    description: "Centralized auth and routing. Handles auth_required ~2x more efficiently than a Server.",
    capabilities: [
      cap("auth", 1, 2),
      cap("rate-limit", 1, 3),
      cap("routing", 1, 3),
      cap("forwarding", 1, 1),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "http", 100)],
    placementCost: 250,
    upgradeCostCurve: [0, 250, 500, 1000],
    visual: { icon: "api-gateway", color: "#ec4899", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "service_registry",
    name: "Service Registry",
    description: "Service discovery. Components register and discover each other.",
    capabilities: [
      cap("registration", 1, 2),
      cap("health-check", 1, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "data", 100), port("out", "egress", "data", 100)],
    placementCost: 150,
    upgradeCostCurve: [0, 150, 300],
    visual: { icon: "registry", color: "#a855f7", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "worker",
    name: "Worker",
    description: "Async batch processor. Pulls jobs from queues instead of receiving pushed traffic.",
    capabilities: [
      cap("batch-processing", 1, 3),
      cap("monitoring", 1, 2),
      cap("auto-scale", 0, 2),
    ],
    ports: [port("in", "ingress", "any", 100), port("out", "egress", "data", 100)],
    placementCost: 125,
    upgradeCostCurve: [0, 125, 250, 500],
    visual: { icon: "worker", color: "#eab308", shape: "rect" },
    conditionProfile: defaultProfile,
  },
  {
    type: "circuit_breaker",
    name: "Circuit Breaker",
    description: "Prevents cascading failures. Opens circuit when downstream is unhealthy.",
    capabilities: [
      cap("circuit-breaker", 1, 3),
      cap("forwarding", 1, 1),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "any", 100), port("out", "egress", "any", 100)],
    placementCost: 100,
    upgradeCostCurve: [0, 100, 200, 400],
    visual: { icon: "circuit-breaker", color: "#ef4444", shape: "octagon" },
    conditionProfile: defaultProfile,
  },
  {
    type: "dns_gtm",
    name: "DNS / Global Traffic Manager",
    description: "Geographic routing to nearest healthy zone. Multi-region architecture enabler.",
    capabilities: [
      cap("geo-routing", 1, 2),
      cap("forwarding", 1, 1),
      cap("health-check", 1, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "http", 100)],
    placementCost: 300,
    upgradeCostCurve: [0, 300, 600],
    visual: { icon: "dns", color: "#14b8a6", shape: "globe" },
    conditionProfile: resilientProfile,
  },
  {
    type: "blob_storage",
    name: "Blob Storage",
    description: "Unstructured asset storage. Cheap capacity, high bandwidth, high base latency.",
    capabilities: [
      cap("blob-storage", 1, 3),
      cap("replication", 0, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "data", 100), port("out", "egress", "data", 100)],
    placementCost: 250,
    upgradeCostCurve: [0, 250, 500, 1000],
    visual: { icon: "blob-storage", color: "#64748b", shape: "rect" },
    conditionProfile: resilientProfile,
  },
  {
    type: "streaming_media_server",
    name: "Streaming Media Server",
    description: "Handles sustained streaming sessions. Adaptive bitrate and chunked delivery.",
    capabilities: [
      cap("streaming", 1, 3),
      cap("caching", 1, 2),
      cap("monitoring", 1, 2),
    ],
    ports: [port("in", "ingress", "http", 100), port("out", "egress", "data", 100)],
    placementCost: 300,
    upgradeCostCurve: [0, 300, 600, 1200],
    visual: { icon: "streaming", color: "#e11d48", shape: "rect" },
    conditionProfile: defaultProfile,
  },
];
